#!/bin/sh

PREREQ=""

prereqs()
{
   echo "$PREREQ"
}


case $1 in
prereqs)
   prereqs
   exit 0
   ;;
esac

. /scripts/functions

current_dev=$(resolve_device "${ROOT}")

if [[ $(blkid "${current_dev}" -s TYPE -o value) = "btrfs" ]] && [[ $(btrfs property get ${rootmnt} ro) != "ro=false" ]]; then # run only on a read only snapshot
	lower_dir=$(mktemp -d -p /)
	ram_dir=$(mktemp -d -p /)
	mount --move ${rootmnt} ${lower_dir} # move new_root to lower_dir
	mount -t tmpfs tmpfs ${ram_dir}
	mkdir -p ${ram_dir}/upper
	mkdir -p ${ram_dir}/work
	mount -t overlay -o lowerdir=${lower_dir},upperdir=${ram_dir}/upper,workdir=${ram_dir}/work rootfs ${rootmnt}
fi

